# Generated by Django 6.0.3 on 2026-03-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('teacher_id', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('gender', models.CharField(choices=[('Male', 'Masculin'), ('Female', 'Féminin')], max_length=10, verbose_name='Genre')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('hire_date', models.DateField(verbose_name="Date d'embauche")),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('qualification', models.CharField(max_length=200, verbose_name='Qualification')),
                ('specialization', models.CharField(max_length=200, verbose_name='Spécialisation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
