# Generated by Django 6.0.3 on 2026-03-31 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0002_department_subject'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'examen")),
                ('exam_type', models.CharField(choices=[('midterm', 'Examen mi-session'), ('final', 'Examen final'), ('quiz', 'Quiz'), ('practical', 'Examen pratique'), ('project', 'Projet')], max_length=20, verbose_name="Type d'examen")),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('room', models.CharField(max_length=50, verbose_name='Salle')),
                ('total_marks', models.IntegerField(default=100, verbose_name='Note totale')),
                ('passing_marks', models.IntegerField(default=50, verbose_name='Note de passage')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='faculty.subject', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField(verbose_name='Note obtenue')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam', verbose_name='Examen')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='student.student', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Résultat',
                'verbose_name_plural': 'Résultats',
                'ordering': ['-exam__date'],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
