# Generated by Django 6.0.3 on 2026-03-31 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0002_department_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'export")),
                ('format', models.CharField(choices=[('json', 'JSON'), ('pdf', 'PDF'), ('html', 'HTML')], default='html', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Données exportées')),
            ],
            options={
                'verbose_name': "Export d'emploi du temps",
                'verbose_name_plural': "Exports d'emplois du temps",
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Lundi'), ('tuesday', 'Mardi'), ('wednesday', 'Mercredi'), ('thursday', 'Jeudi'), ('friday', 'Vendredi'), ('saturday', 'Samedi')], max_length=20, verbose_name='Jour')),
                ('time_slot', models.CharField(choices=[('08:00', '08:00 - 09:30'), ('09:45', '09:45 - 11:15'), ('11:30', '11:30 - 13:00'), ('14:00', '14:00 - 15:30'), ('15:45', '15:45 - 17:15'), ('17:30', '17:30 - 19:00')], max_length=10, verbose_name='Horaire')),
                ('classroom', models.CharField(max_length=50, verbose_name='Salle de classe')),
                ('group', models.CharField(blank=True, max_length=50, verbose_name='Groupe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='faculty.subject', verbose_name='Matière')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='faculty.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Emploi du temps',
                'verbose_name_plural': 'Emplois du temps',
                'ordering': ['day', 'time_slot'],
                'unique_together': {('day', 'time_slot', 'classroom')},
            },
        ),
    ]
